### ISSUE TITLE
performance module

### ISSUE THREAD

**Issue by babyhands1123** [ematvey/pybacktest#16]
Hello there, I'm sorry for the trivial question, I have an issue when I'm importing the module the performance function wouldn't load, it throws an error "cannot import name performance". 

I'm sorry I really couldn't find the answer on stack. 

I'm using Anaconda environment, do you think it can be python compatibility issue ?

**Comment by ematvey** [comment]
Can you post some code to reproduce?

**Comment by ematvey** [comment]
Can you post some code that reproduces the error?

**Comment by guarita** [comment]
I had the problem here. I have anaconda2 installed and just installed pybacktest and pandas-datareader with 'pip' (as specified on the main page) and 'conda' respectively.

I received the same message  when I ran import pybacktest on spyder right after installing: 

```
import pybacktest
Traceback (most recent call last):

  File "<ipython-input-2-94728f624981>", line 1, in <module>
    import pybacktest

  File "/home/guarita/anaconda2/lib/python2.7/site-packages/pybacktest/__init__.py", line 3, in <module>
    from . import performance

ImportError: cannot import name performance
```

When I did reset spyder everything was fine, the command ran without any problem.

I'm on a Ubuntu 16.04.1 platform, 64 bit edition with Anaconda 2.

**Comment by ematvey** [comment]
Yeah, relative imports I used back then are kind of antipattern and might lead to problems in different environments. Fixed it, thanks for the report!
